package com.java.innerclasses;
/**
 * 
 * @author skatt
 * Member Inner Class
 */

//Outer Class
public class Car {
	 private int cost=30000;  
	 
	 //Inner Class
	 class Engine{  
		 void msg(){
			 System.out.println("The Cost of the Car is "+cost);
		}  
	 }  
	 
	 public static void main(String args[]){  
		 Car outerObject = new Car();  //Instantiating Outer Class Object
		 Car.Engine inner = outerObject.new Engine();  //Instantiating Inner Class Object
		 inner.msg();  
	 }  
}  

//Internal code generated by the compiler
//
//
//import java.io.PrintStream;  
//class Car$Engine  
//{  
//    final Car this$0;  
//    Car$Engine()  
//    {   super();  
//        this$0 = Car.this;  
//    }  
//    void msg()  
//    {  
//        System.out.println((new StringBuilder()).append("data is ")  
//                    .append(Car.access$000(Car.this)).toString());  
//    }  
//}  
